name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - emby-support  # Trigger on push to main branch
  pull_request:
    branches:
      - emby-support  # Trigger on pull requests to main branch

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/therealjin/membarr:latest .

      - name: Push Docker image
        run: |
          docker tag ghcr.io/therealjin/membarr:latest ghcr.io/therealjin/membarr:${{ github.sha }}
          docker push ghcr.io/therealjin/membarr:latest
          docker push ghcr.io/therealjin/membarr:${{ github.sha }}
